#! /bin/sh
# /etc/init.d/opr-client

### BEGIN INIT INFO
# Provides:          opr-client
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OPR Client initscript
### END INIT INFO

case "$1" in
   start)
    echo "Starting opr-client"
    /usr/bin/node /home/pi/services/opr-client/index.js >> /home/pi/services/opr-client/opr-client.log &
   ;;
   stop)
    echo "Stopping opr-client"
    killall -9 node
    ;;
  *)
    echo "Usage: /etc/init.d/opr-client {start|stop}"
    exit 1
    ;;
esac

exit 0
